### ISSUE TITLE
Bug scanimage example - wrong device ID created

### ISSUE THREAD

**Issue by Matthias84** [janrueth/es2button#1]
Hi, thank you for creating this nice service :smile: 

While playing to integrate to my environment, I stumbled upon problems with 'example-scanimage.sh' that blocks to scan an image:

> matthias@flunder:/etc/es2button$ journalctl -f
> Jun 04 15:22:58 flunder es2button[3835]: Output format is not set, using pnm as a default.
> Jun 04 15:22:58 flunder es2button[3835]: scanimage: open of device epsonscan2:DS-310:004:004:esci2:usb::345 failed: Invalid argument
> Jun 04 15:22:58 flunder es2button[3823]: Finished scan
> Jun 04 15:22:58 flunder es2button[3822]: /
> matthias@flunder:/etc/es2button$ scanimage -L
> device `epsonscan2:DS-310:004:004:esci2:usb:ES013E:345' is a EPSON DS-310:004:004 flatbed scanner

So the PID seems to empty? Is this caused by my previous installed epsonscan2 installation? :thinking:

**Comment by janrueth** [comment]
Hey,

looks like the `model` variable in the script is unset which should be `ES013E`.

As there seems to be no way to get the model name from the scanner itself, the script relies on some files installed by the epsonscan2 package which do contain the mappings between device ids and model names.

Mind checking if you do have the following file on your system (this should be installed through epsonscan2) by executing this command and posting the output here:
```
ls /usr/lib/$(uname -m)-linux-gnu/epsonscan2/Resources/Models/ES013E/US/ES013E.json
```

What distribution and architecture (aarch64 or x86?) are you using?

**Comment by Matthias84** [comment]
The command works fine:
`matthias@flunder:~/scans$ ls /usr/lib/$(uname -m)-linux-gnu/epsonscan2/Resources/Models/ES013E/US/ES013E.json
/usr/lib/x86_64-linux-gnu/epsonscan2/Resources/Models/ES013E/US/ES013E.json
`
Pretty confusing, as this is a almost stock Ubuntu 22.10 x64 :thinking:

**Comment by janrueth** [comment]
Hmm,
I haven't yet tried it on x64... but I don't know why that shouldn't work.

Since you say stock. Do you have `jq` installed? This looks like the only command that might not be installed on a stock OS that the script uses.

The script creates a file called `.lut.json` on the first run using the following command
```
find /usr/lib/$(uname -m)-linux-gnu/epsonscan2/Resources/Models/ | grep -E "/ES[^/.]+\.json$" | xargs -I {} jq '{"model": "'{}'", "PID": .HardwareInfo[0].ESProductID.string}' {}
```

If you execute this manually, you should see a lot of lines like:
```
{
  "model": "/usr/lib/aarch64-linux-gnu/epsonscan2/Resources/Models/ES0254/ALL/ES0254.json",
  "PID": "11A9"
}
{
  "model": "/usr/lib/aarch64-linux-gnu/epsonscan2/Resources/Models/ES019E/ALL/ES019E.json",
  "PID": "115F"
}
....
```

In what folder are you executing the script? Since the script writes a file, that folder needs to be writable.
I think by default it should run with `/root` as the working directory which is where the `.lut.json` should be. So you might also want to check if that file is present and if that has content like above.

You might want to add a `set -xe` at the start of the script (next line after `#!/bin/bash`) to see what it executes and whether or not something in the script fails.

**Comment by janrueth** [comment]
Hey,

I created a small change that loads the model names from the epsonscan2 resource folder and makes the one matching the current usb product id available to the script.

Mind testing the changes in https://github.com/janrueth/es2button/pull/2 ? I haven't fully tested it yet, as I'm not near my scanner 😅

**Comment by Matthias84** [comment]
_Hi Jan, I'm sorry for beeing late, but RL keept me busy_

I checked out your PR and readded the 0.3 es2button package. Unfortunatly there seems to be still  a minor bug that prevents scanning

> Jun 29 20:31:03 flunder es2button[2599]: Button 1 pressed on DS-310:004:002 (013E) (VID:PID=04B8:0159)
> Jun 29 20:31:03 flunder es2button[2599]: Starting scan
> Jun 29 20:31:03 flunder es2button[2599]: Scanning A4 paper
> Jun 29 20:31:03 flunder es2button[2603]: Output format is not set, using pnm as a default.
> Jun 29 20:31:04 flunder es2button[2603]: scanimage: open of device epsonscan2:DS-310:004:002:esci2:usb:013E:345 failed: Invalid argument
> Jun 29 20:31:04 flunder es2button[2599]: Finished scan
> matthias@flunder:/etc/es2button$ scanimage -L
> device `epsonscan2:DS-310:004:002:esci2:usb:ES013E:345' is a EPSON DS-310:004:002 flatbed scanner

Will try tomorrow to figure out whats the probelm with default `example-scanimage.sh`. Thanks anyway :+1:

**Comment by janrueth** [comment]
ohh I think I see the issue. I missed adding an `ES` prefix before the `013E` in the command that executes the scanimage command.

**Comment by Matthias84** [comment]
True, addind "ES" prefix makes the scanner working as intended :+1:

**Comment by janrueth** [comment]
Should be fixed on the recent changes in main
