### ISSUE TITLE
No network device support?

### ISSUE THREAD

**Issue by scrapix** [janrueth/es2button#12]
Hi Jan, is this utility meant to be used for scanners connected via USB?
Otherwise I can't figure out how to make the connection to my network-connected Epson scanner.

**Comment by janrueth** [comment]
Yeah, this is totally meant for usb. Maybe it‘s possible to have the same functionality for networked devices, but I don‘t have one, so I don‘t know

**Comment by scrapix** [comment]
Thank your for your reply. I figured that epson network connections need a paring which the linux version of epsonscan2 apparently does not support. So USB it'll be! Thank you for your great work!
