### ISSUE TITLE
failed handling button press: Invalid Parameter

### ISSUE THREAD

**Issue by caraar12345** [janrueth/es2button#8]
Hello!

Thanks for this -- it's awesome and exactly what I need!

However, I'm having some trouble getting it to work with my Epson WF-2935 printer/scanner on a Raspberry Pi 5 running Debian 12.5 Bookworm. Unfortunately, it seems that `libtiff5` and `libwebp6` aren't available on Bookworm so I installed the `.deb` files from the Debian package site directly which _seemed_ to work, but it might well be the problem.

In saying that, I had no problem building Epson Scan 2 directly from Epson - just your arm64 build of ES2 failed to install without them (and building it failed even with the Dockerfile because of `Unknown CMake command "QT5_USE_MODULES"`. 

I have just seen though that building and/or installing ES2 shouldn't be necessary for the Rust remake.

---

When setting it up with the Rust rewrite of `es2button`, I'm seeing this:

```
May 03 11:59:55 pi5 es2button[82861]: [ERROR es2button::listener] failed handling button press: Invalid Parameter
```

And then the printer starts yelling about a `Communication error`.

Is there anything you'd recommend to be able to pin down what the Invalid Parameter is?

Cheers!

**Comment by janrueth** [comment]
You do still need to install epsonscan2.

Let me investigate this further. I‘ve actually never run it without, if that is the curlpit, the error should indicate that then

**Comment by caraar12345** [comment]
I believe I do have Epson Scan 2 installed (I built it from the epson source directly); seems that the Invalid Parameter is an ES2 error as I found the error string in the ES2 source (I can't link to it right now as I'm not at a computer)

**Comment by janrueth** [comment]
Mind starting the program with the following environment variable:
```
RUST_LOG=TRACE
```

i.e., it can just be prefixed to the command:
```
RUST_LOG=TRACE es2button [...args]
```

This should give more insights into where it is failing. But generally, it seems it would aid if I added more context to where these errors originate.

**Comment by janrueth** [comment]
I've added a new release that should also help localize the problem better: https://github.com/janrueth/es2button/releases/tag/v0.3.1

Mind running that and reporting back what it says?

**Comment by caraar12345** [comment]
Thank you! Sorry for the delay 🙇 

Seems as though it's because my printer doesn't support card scanning -- so should just be a case of error handling at the card scanning check..?

```rust
[TRACE es2button::listener] Connecting: {"ConnectionSetting":[{"ConnectType":{"int":0},"VID":{"int":1208},"PID":{"int":4526},"BUS_NUMBER":{"int":1},"DEVICE_NUMBER":{"int":6}}]}
Button 2 pressed in wrapper, dispatching to 0x5555bbd0b6e4
[DEBUG es2button::listener] Button pressed: 2
[TRACE es2button::listener] Checking scanner document state
[TRACE es2command::scanner] Got value from scanner, for key: documentLoaded, value: {
        "documentLoaded": {
            "boolean": false
        }
    }
[ERROR es2button::listener] failed handling button press: checking card scanning: Invalid Parameter
```

**Comment by caraar12345** [comment]
Confirmed to be the card scanning as this worked for me 😂 

```diff
index 0e2b50f..dc82bc5 100644
--- a/es2button/src/listener.rs
+++ b/es2button/src/listener.rs
@@ -86,7 +86,8 @@ impl<'a> Listener<'a> {
         let doc_present = self
             .is_document_loaded()
             .context("checking document status")?;
-        let card_scanning = self.is_card_scanning().context("checking card scanning")?;
+        //let card_scanning = self.is_card_scanning().context("checking card scanning")?;
+        let card_scanning = false;

         trace!("Disconnecting from scanner");
         self.scanner.close().context("closing scanner")?;
```

**Comment by janrueth** [comment]
well, I only tested this with mine, I figured it would just report no card scanning by default if it wasn't available. Let me add some code that catches the error and simply returns false in that case

**Comment by caraar12345** [comment]
That would have been sensible of Epson...! 

Thank you - I tried to have a crack at it but it turns out error handling is quite difficult if you've not even printed "hello, world" in rust 😂

**Comment by janrueth** [comment]
https://github.com/janrueth/es2button/releases/tag/v0.3.2 should include the fix
